In [1]:
import numpy as np
from tqdm import tqdm
import matplotlib.pyplot as plt
from scipy.signal import medfilt
import pickle


In [2]:
class Config():
    def __init__(self):        
        self.frame_l = 32 # the length of frames
        self.joint_n = 22 # the number of joints
        self.joint_d = 3 # the dimension of classes        
        self.data_dir = '/media/l/data/HRC/HRC_intention_recognition/code/HRC_data/HandGestureDataset_SHREC2017/'
        self.save_dir = '/media/l/data/HRC/HRC_intention_recognition/code/DD-Net-master/data/SHREC/'

C = Config()

In [3]:
train_list = np.loadtxt(C.data_dir +'train_gestures.txt').astype('int16')
test_list = np.loadtxt(C.data_dir +'test_gestures.txt').astype('int16')


In [4]:
print(train_list)

[[  1   1   2 ...   1   1  77]
 [  1   1   2 ...   1   1 117]
 [  1   1   2 ...   1   1  92]
 ...
 [ 14   2  27 ...  14  28  56]
 [ 14   2  27 ...  14  28  55]
 [ 14   2  27 ...  14  28  58]]


In [5]:
Train = {}
Train['pose'] = []
Train['coarse_label'] = []
Train['fine_label'] = []

for i in tqdm(range(len(train_list))):
    idx_gesture = train_list[i][0]
    idx_finger = train_list[i][1]
    idx_subject = train_list[i][2]
    idx_essai = train_list[i][3]
    coarse_label = train_list[i][4]
    fine_label = train_list[i][5]
    
    skeleton_path = C.data_dir + '/gesture_' + str(idx_gesture) + '/finger_' \
                + str(idx_finger) + '/subject_' + str(idx_subject) + '/essai_' + str(idx_essai)+'/'
        
    p = np.loadtxt(skeleton_path+'skeletons_world.txt').astype('float32')
#     print(p.shape)
#     print(p.shape[1])
    for j in range(p.shape[1]): #p.shape[1] 66: 22*3
        p[:,j] = medfilt(p[:,j])
        
    Train['pose'].append(p)
    Train['coarse_label'].append(coarse_label)
    Train['fine_label'].append(fine_label)
    

100%|██████████| 1960/1960 [00:22<00:00, 88.10it/s] 


In [6]:
pickle.dump(Train, open(C.save_dir+"train.pkl", "wb"))

In [7]:
Test = {}
Test['pose'] = []
Test['coarse_label'] = []
Test['fine_label'] = []

for i in tqdm(range(len(test_list))):
    idx_gesture = test_list[i][0]
    idx_finger = test_list[i][1]
    idx_subject = test_list[i][2]
    idx_essai = test_list[i][3]
    coarse_label = test_list[i][4]
    fine_label = test_list[i][5]
    
    skeleton_path = C.data_dir + '/gesture_' + str(idx_gesture) + '/finger_' \
                + str(idx_finger) + '/subject_' + str(idx_subject) + '/essai_' + str(idx_essai)+'/'
        
    p = np.loadtxt(skeleton_path+'skeletons_world.txt').astype('float32')
    for j in range(p.shape[1]):
        p[:,j] = medfilt(p[:,j])
        
    Test['pose'].append(p)
    Test['coarse_label'].append(coarse_label)
    Test['fine_label'].append(fine_label)
    

100%|██████████| 840/840 [00:08<00:00, 94.42it/s] 


In [8]:
pickle.dump(Test, open(C.save_dir+"test.pkl", "wb"))

In [9]:
Test = pickle.load(open(C.save_dir+"test.pkl", "rb"))